* کانکت - بازی گروهی

** پیش‌نیازها
- یک جمع دست کم ۴ نفره 
- دل خوش :) 
  
** روش بازی
یک نفر که مجری هر مرحله می‌شود یک کلمه در ذهن خود انتخاب و سپس حرف اول آن را اعلام می‌کند. این نفر را مجری بازی می‌نامیم.
هدف باقی افراد این است که این کلمه را حدس بزنند. روش حدس زدن به این صورت است که هر شخص یک کلمه را حدس می‌زند ولی در ذهن خود نگه می‌دارد و بر اساس کلمه در ذهن خود یک نشانی به بقیه می‌دهد. 

فرض کنیم که مجری، حرف ب را اعلام کرده است (مثلا به خاطر کلمه بیتا ) یک نفر کلمه ببر را حدس زده است به جای اعلام صریح کلمه ببر، باید آن را طوری در لفافه اعلام کند که مجری آن را حدس نزند ولی دست کم یک نفر از جمع آن را حدس بزند
مثلا اعلام کند حیوان درنده و یکی دیگر غیر از مجری باید با این اشاره به کلمه ببر برسد. نکته اینجاست که مجری هم می‌تواند با این اشاره به کلمه ببر برسد، شاید اعلام کردن چیزی مثل "چیزی که دیروز پس‌زمینه لپ‌تاپ  فلانی بود"
با این هدف که "فلانی" و/یا کسی که در جمع بوده و این عکس را دیده آن را حدس بزند و نه مجری. 
اگر مجری در هر زمانی کلمه مورد نظر بازیکن را حدس زد، باید اعلام کند که مثلا "ببر نیست" حال اگر کس دیگری این کلمه را حدس زد می‌گوید " کانکت" و به محض کانکت شدن این دو نفر باید شروع به شمردن از ۱۰ تا صفر می‌کنند. 
در هر زمانی که مجری بتواند این کلمه را حدس بزند باید آن را اعلام کند که مثلا فلان کلمه نیست - که در مثال ما می‌گوید ببر نیست-، به این ترتیب ارتباط قطع شده و اصطلاحا دیسکانکت می‌شوند. اگر مجری کلمه درستی را حدس نزد ولی مرتبط با سوال پرسیده شده بود (مثلا برای حیوان
با حرف ب، بلبل را حدس زد به جای ببر، شمردن باید مجدد از ۱۰ شروع می‌شود) 
اما اگر تا پایان ۱۰ شماره مجری کلمه را حدس نزد، دو نفر کانکت شده باید آن را همزمان و به جای شماره صفر اعلام کنند. اگر هر دو واقعا یک کلمه در ذهنشان باشد، مجری باید حرف بعدی کلمه موردن ظر خودش را اعلام کند (در اینجا ی) و بازی این بار با دو حرف «بی» ادامه پیدا می‌کند. این روند آن‌قدر ادامه پیدا می‌کند که کلمه اصلی حدس زده شود. 

** قوانین بازی
- مجری می‌تواند کلمه خود را هر زمانی که خواست عوض کند. به این شرط که کلمه همچنان در همان حروفی که تا زمان تغییر کشف شده، مشترک باشد، دوم این که کلمه قبلا در همین بازی توسط دیگران اعلام نشده باشد. 
- در نسخه اولیه بازی، همیشه مجری بالاخره بازنده است. بر مبنای پیشنهاد ما، کسانی که اشتباه کانکت می‌کنند (یعنی در شماره صفر مشخص می‌شود هر کدام چیز دیگری در نظر داشته‌اند) را می‌توان از این دست بازی محروم کرد و اگر همه حذف شوند مجری برنده است

*** قوانین بازی با تعداد زیاد
- اگر تعداد زیاد باشد، می‌توان حتی کانکشن‌های دیسکانکت شده را هم حذف کرد که مجری برنده شود.
- در بازی با تعداد زیاد افرادی که می‌خواهند کلمه‌ای حدس بزنند باید دست خود را بالا گرفته و درخواست گفتن حدس خود را بدهند، مجری در هر اجرا به یکی از افرادی که در انتظار حدس زدن کلمه هستند اجازه می‌دهد حدس خود را بیان کند.

*** قوانین انتخابی
- هربار که شمارش معکوس از سر گرفته می‌شود، می‌توان یک ثانیه از مهلت مجری کم کرد که از پراکنده‌گویی وی جلوگیری شود. به این ترتیب که برای دومین حدس به وی نه ثانیه وقت داده شود، برای سومین حدس هشت ثانیه و همین‌طور تا پایان. البته اگر چنین قانونی را انتخاب نکنید بهتر است زیرا همان شمارش به اندازه کافی به مجری استرس وارد می‌کند و مانع از تمرکز وی برای حدس کلمه شود و به علاوه نبود چنین قانونی به افزایش تمرین برای تمرکز برای شرایط پراسترس و هیجانی کمک شایانی می‌کند.

*** بازی گروهی
- می‌توان این بازی را بین دو گروه نیز انجام داد. در این حالت گروه مجری سعی می‌کنند با هم، گروه مقابل را دیسکانکت کنند.
- نوبت‌دهی بین دو گروه می‌تواند به روش‌های مختلفی انجام شود.
  - این که هر گروه به نوبت، کلمه‌ای را انتخاب کند و نقش مجری را داشته باشد. پس از پیدا شدن تمام کلمه، نوبت به گروه مقابل می‌رسد.
  - این که هر دو گروه کلمه‌ای انتخاب کنند، یک گروه شروع به بازی کند، اگر نتوانست ظرف مدت معینی، مثلا یک دقیقه، حداقل یک حرف از کلمه گروه مقابل را بیابد، نوبت به گروه مقابل می‌رسد. در واقع فاصله بین دو کانکت موفق باید کمتر از مدت معینی باشد. در این حالت سرعت و هیجان بازی بالاتر می‌رود.
  - می‌توان برای رعایت انصاف کلمات با طول یکسان انتخاب کرد، اما نباید فراموش کرد که در واقع پیشرفت بازی به در مهارت اعضای گروه در کانکت کردن و پیدا کردن حرف بعدی است که ربطی به کلمه انتخاب شده ندارد.
