* کانکت - بازی گروهی

** پیشنیازها
- یک جمع دست کم ۴ نفره 
- دل خوش :) 
  
** روش بازی
یک نفر که مجری مرحله میشود یک کلمه در ذهن خود انتخاب میکند و سپس حرف اول آنرا اعلام میکند. این نفر را مجری بازی مینامم.
هدف باقی افراد این است که این کلمه را حدس بزنند. روش حدس زدن به اینصورت است که هر شخص یک کلمه را حدس میزند ولی در ذهن خود نگه میدارد و بر اساس کلمه در ذهن خود یک نشانی به بقیه میدهد. 

فرض کنیم که مجری، حرف ب را اعلام کرده است (مثلا به خاطر کلمه بیتا ) یک نفر کلمه ببر را حدس زده است به جای اعلام صریح کلمه ببر، باید آنرا طوری در لفافه اعلام کند که مجری آنرا حدس نزند ولی دست کم یک نفر از جمع آنرا حدس بزند
مثلا اعلام کند حیوان درنده. و یکی دیگر غیر از مجری باید با این اشاره به کلمه ببر برسد. نکته اینجاست که مجری هم میتواند با این اشاره به کلمه ببر برسد، شاید اعلام کردن چیزی مثل "چیزی که دیروز تو بک گراند لپتاب فلانی بود "
با این هدف که "فلانی" , و یا کسی که در جمع بوده و این عکس را دیده آنرا حدس بزند و نه مجری. 
اگر مجری در هر زمانی کلمه مورد نظر بازیکن را حدس زد، باید اعلام کند که مثلا "ببر نیست " اگر کس دیگری این کلمه را حدس زد میگوید " کانکت" و به محض کانکت شدن این دو نفر باقی شروع به شمردن از ۱۰ تا صفر میکنند. 
در هر زمانی که مجری بتواند این کلمه را حدس بزند باید آنرا اعلام کند، به این ترتیب ارتباط قطع شده و اصطلاحا دیسکانکت میشوند. اگر مجری کلمه درستی را حدس نزد ولی مرتبط با سوال پرسیده شده بود (مثلا برای حیوان
با حرف ب، بلبل را حدس زد به جای ببر، شمردن مجددا از ۱۰ شروع میشود) 
اما اگر تا پایان ۱۰ شماره مجری کلمه را حدس نزد، دو نفر کانکت شده باید آنرا همزمان و به جای شماره صفر اعلام کنند. اگر هر دو واقعا یک کلمه در ذهنشان باشد، مجری باید حرف بعدی کلمه موردنظر خودش را اعلام کند (در اینجا ی) و بازی اینبار با دو حرف بی ادامه پیدا میکند. این روند انقدر ادامه پیدا میکند که کلمه اصلی حدس زده شود. 

** قوانین بازی
- مجری میتواند کلمه خود را هر زمانی که خواست عوض کند. به این شرط که کلمه همچنان در همان حروف مشترک باشد، و دوم اینکه کلمه قبلا در همین بازی توسط دیگران اعلام نشده باشد. 
- در نسخه اولیه بازی، همیشه مجری بالاخره بازنده است.  برمبنای پیشنهاد ما، کسانی که اشتباه کانکت میکنند (یعنی در شماره صفر مشخص میشود هر کدام چیز دیگری در نظر داشته‌اند) را میتوان از این دست بازی محروم کرد و اگر همه حذف شوند مجری برنده است

  ** قوانین بازی با تعداد زیاد
- اگر تعداد زیاد باشد میتوان حتی کانکشن های دیسکانکت شده را هم حذف کرد که مجری برنده شود.
- در بازی با تعداد زیاد افرادی که می‌خواهند کلمه‌ای حدس بزنند باید دست خود را بالا گرفته و درخواست گفتن حدس خود را بدهند، مجری در هر اجرا به یکی از افرادی که در انتظار حدس زدن کلمه هستند اجازه می‌دهد حدس خود را بیان کند.

  ** قوانین انتخابی
- هربار که شمارش معکوس از سر گرفته می‌شود، می‌توان یک ثانیه از مهلت مجری کم کرد که از پراکنده‌گویی وی جلوگیری شود. به این ترتیب که برای دومین حدس به وی نه ثانیه وقت داده شود، برای سومین حدس هشت ثانیه و همین‌طور تا پایان
